export const macros = {
  "\\N": "\\mathbb{N}",
  "\\Nn": "\\mathbb{N}",
  "\\R": "\\mathbb{R}",
  "\\Rr": "\\mathbb{R}",
  "\\Z": "\\mathbb{Z}",
  "\\Zz": "\\mathbb{Z}",
  "\\Kk": "\\mathbb{K}",
  "\\Q": "\\mathbb{Q}",
  "\\Cp": "\\mathbb{C}",
  "\\CC": "\\mathbb{C}",
  "\\RRe": "\\mathrm{Re}",
  "\\IIm": "\\mathrm{Im}",
  "\\C": "\\mathbb{C}",
  "\\im": "{\\mathrm{i}",
  "\\EX": "\\mathbb{E}",
  "\\E": "\\mathbb {E}",
  "\\var": "\\mathrm{Var}",
  "\\Sol": "\\mathscr{S}",
  "\\PP": "\\mathrm{P}",
  "\\prob": "\\mathrm{P}",
  "\\OIJ": "($O$;$\\overrightarrow{\\imath}",
  "\\uu": "\\overrightarrow{u}",
  "\\vv": "\\overrightarrow{v}",
  "\\ww": "\\overrightarrow{w}",
  "\\Pn": "\\mathscr{P}",
  "\\Pnn": "\\mathscr{P}",
  "\\dx": "\\hspace{.6mm}",
  "\\dt": "\\hspace{.6mm}",
  "\\p": "\\mathrm{P}",
  "\\nd": "\\noindent}",
  "\\ssi": "si, et seulement si,}",
  "\\mq": "Montrer que}",
  "\\ep": "\\varepsilon}",
  "\\cad": "c'est-à-dire}",
  "\\1": "\\mathbf{1}",
  "\\dy": "\\hspace{.6mm}",
  "\\dz": "\\hspace{.6mm}",
  "\\du": "\\hspace{.6mm}",
  "\\dv": "\\hspace{.6mm}",
  "\\n": "_{n\\in\\N}",
  "\\nstar": "_{n\\in\\N^*}",
  "\\eq": "\\;\\Leftrightarrow\\;}",
  "\\impl": "\\;\\Rightarrow \\;}",
  "\\va": "variable aléatoire}",
  "\\vas": "variables aléatoires}",
  "\\lr": "\\longrightarrow}",
  "\\vide": "\\varnothing}",
  "\\dd": "\\textup{d}",
  "\\dlim": "\\displaystyle\\lim}"
};